# Generated by Django 4.2.7 on 2026-04-22 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_primary_coach_from_programs(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    TrainingProgram = apps.get_model('programs', 'TrainingProgram')
    athlete_ids = TrainingProgram.objects.values_list('athlete_id', flat=True).distinct()
    for aid in athlete_ids:
        prog = TrainingProgram.objects.filter(athlete_id=aid).order_by('-updated_at').first()
        if prog:
            User.objects.filter(pk=aid, user_type='athlete').update(primary_coach_id=prog.coach_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bodyweight_gender"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="primary_coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_roster_athletes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_coaches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("head_coach", "Head Coach"),
                    ("coach", "Coach"),
                    ("athlete", "Athlete"),
                ],
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill_primary_coach_from_programs, migrations.RunPython.noop),
    ]
