# Generated by Django 4.2.7 on 2026-04-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0002_programcompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalrecord",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="personalrecord",
            index=models.Index(
                fields=["athlete", "lift_type", "-date"],
                name="pr_athlete_lift_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="programcompletion",
            index=models.Index(
                fields=["athlete", "-updated_at"], name="completion_athlete_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["athlete", "-date"], name="workoutlog_athlete_date_idx"
            ),
        ),
    ]
